### ISSUE TITLE
Test with faulty peer

### ISSUE THREAD

**Issue by ustulation** [maidsafe/quic-p2p#30]
Test cases for:

0. A faulty peer (node or client) that doesn't successfully complete handshake within a give period of time does not keep our resources unresolved with tokio forever and the incomplete connection is severed.
1. Check for scenarios that a faulty peer can get us into and make sure they don't cause us harm

**Comment by nbaksalyar** [comment]
Covered by https://github.com/maidsafe/quic-p2p/pull/45
