### ISSUE TITLE
use structopts

### ISSUE THREAD

**Issue by ustulation** [maidsafe/quic-p2p#38]
Use this to pass config and other options to `quic-p2p`.

**Comment by dirvine** [comment]
Lets test this for allowing upper libs to use structopt and flatten our options giving them great cmd line handling, but also allow the override in the API where folk can pass the vector of config items structop type struct can use. That way users can use cmd line and we have it for them or they can pass in config opts, however they get them.

**Comment by nbaksalyar** [comment]
Addressed by #40
