### ISSUE TITLE
quic-p2p vs crust

### ISSUE THREAD

**Issue by caemor** [maidsafe/quic-p2p#71]
Will quic-p2p replace crust or ẁill it be added as an additional protocol, respectively what are the plans in the future for both of them?

Greetings,
Chris

**Comment by dirvine** [comment]
HI @caemor it is a replacement. Allows us to handle secured p2p connections and do so in a manner that makes the traffic look very similar to other web based traffic. So many more nice features as well such as stream multiplexing etc.

**Comment by caemor** [comment]
Thanks for the quic answer ;-)
