### ISSUE TITLE
Chat example

### ISSUE THREAD

**Issue by caemor** [maidsafe/quic-p2p#72]
Hello,
I can't get the chat example running since `ourinfo` always returns an error, I can't copy any information to use the `addpeer` command
```
>> ourinfo
Error getting ourinfo: There's no endpoint echo server to ask. Current network configuration
```

Do I need to add a certain configuration on startup?

Thanks in advance

**Comment by nbaksalyar** [comment]
Hello @caemor!
This means the chat couldn't use any public echo server to find out your IP. If you run it locally, or if you know your public IP address already, you can run the example like this:
```
cargo run --example chat -- --ip 127.0.0.1
```
Please let me know if this doesn't work for you.

**Comment by caemor** [comment]
```
~/g/quic-p2p ❯❯❯ cargo run --example chat -- --ip "127.0.0.1"
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/examples/chat --ip 127.0.0.1`


             _                  ____                _           _
  __ _ _   _(_) ___        _ __|___ \ _ __      ___| |__   __ _| |_
 / _` | | | | |/ __| ____ | '_ \ __) | '_ \    / __| '_ \ / _` | __|
| (_| | |_| | | (__ |____|| |_) / __/| |_) |  | (__| | | | (_| | |_
 \__, |\__,_|_|\___|      | .__/_____| .__/    \___|_| |_|\__,_|\__|
    |_|                   |_|        |_|


Type 'help' to get started.
>> ourinfo
Error getting ourinfo: There's no endpoint echo server to ask. Current network configuration
``` 

Still getting the same error. 
I am using :

`
active toolchain
----------------
stable-x86_64-unknown-linux-gnu (default)
rustc 1.37.0 (eae3437df 2019-08-13)
`

The bootstrap+client node is working for me :thinking:
