### ISSUE TITLE
Bring mock quic_p2p into quic p2p crate

### ISSUE THREAD

**Issue by jeanphilippeD** [maidsafe/quic-p2p#86]
Bring the mock quic_p2p/Network object needed to run both routing and vaults on mock network.

Decision:
https://maidsafe.slack.com/archives/C072L6WGH/p1578412061321200?thread_ts=1578409118.307500&cid=C072L6WGH

> Adam Cigánek  12 minutes ago
I think taking mock-quic-p2p out of routing and making it its own crate (or part of real quic-p2p behind a feature flag) would probably clarify lot of the confusion here.

> Jean-Philippe Dufraigne  8 minutes ago
Would that address your concerns @dirvine?

> David Irvine  3 minutes ago
Yes @jean mostly. I would also be in favour of making all the routing mock stuff not accessible to any others right now. The visibility/api changes we make with mock for testing should not be available to others. Until we can separate that out then I would say we must make the mock flags private to routing. (edited) 

> Jean-Philippe Dufraigne  3 minutes ago
@dirvine would you favor the one crate solution (in quic_p2p like it is for threshold_crypto, probably simpler) or 2 crate a new test crate/repo? (edited) 

> David Irvine  1 minute ago
I reckon for speed and being in line with others right now the single crate is cool JP. It keeps it all together really. I also think later the mock parsec should be in parsec for the same reasons, again not changing the parsec API.

**Comment by madadam** [comment]
Closed via https://github.com/maidsafe/quic-p2p/pull/87
